services:
  account-service:
    container_name: account-service
    image: account-service:current
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5430/spring # removed from application.yml and added here
    depends_on:
      - postgres-db
      - api-gateway
      - eureka-server

  order-service:
    container_name: order-service
    image: order-service:current
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5430/spring
    depends_on:
      - postgres-db
      - api-gateway
      - eureka-server

  api-gateway:
    container_name: api-gateway
    image: api-gateway:current
    ports:
      - "8080:8080"
    expose:
      - "8080"

  eureka-server:
    container_name: eureka-server
    image: eureka-server:current
    ports:
      - "8761:8761"
    expose:
      - "8761"

  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5430:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring
