services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5430:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring